arpes:
  dataset: RbTiBi/map
  energy:
    delta: -0.01
    flip: true
    npts: 111
    start: 1.06
  kx_angle:
    delta: 0.0448678
    flip: false
    npts: 700
    start: -20.3729
  ky_angle:
    delta: 1.0
    flip: false
    npts: 36
    start: -7.3251
  path: /home/dengxw/ARPES/mapping/data/theory/dataCliu.h5
  work_function: 16.03
calibration:
  dft_hsps:
    manual: true
    rotation_angle: 30.0
    scale: 0.79
  hsps:
    manual: true
    rotation_angle: 27.8
    scale: 0.87
  kx_grid_shift: 0.0
  kx_shift: 0.05150417962962628
  ky_grid_shift: 1.1102230246251565e-16
  ky_shift: 0.05441807228915785
dft:
  csv_file: extracted_data.csv
  fermi_file: BAND_GAP
  k_grid:
  - 20
  - 20
  output_grid:
  - 101
  - 101
  path: /home/dengxw/ARPES/share_data/RbTiBi/Raw_Data
  drop_top_bands: 33
lattice:
  a: 5.8077
  alpha: 90.0
  b: 5.8077
  beta: 90.0
  c: 9.1297
  gamma: 120.0
mrf:
  bands:
  - index: 0
    eta: 0.05
  - index: 1
    eta: 0.05
  - index: 2
    eta: 0.05
  - index: 3
    eta: 0.05
  - index: 4
    eta: 0.05
  bsfi:
    fine_tune_range: 0.05
    offset_range: 1.5
    offset_step: 0.1
    ridge_sigma: 0.1
    weights:
      correlation: 0.6
      intensity: 0.3
      path_ridge: 0.8
      ridge: 0.5
      snr: 0.1
  max_shift: 10
  num_epochs: 10
  alignment: hsp
  offset_mode: per_band
  path_interp_method: cubic
  path_sample_step: 0.005
  smooth_sigma:
  - 0.5
  - 0.5
  - 0.1
preprocessing:
  auto_grid: true
  kd_radius: 0.05
  method: kdtree
  n_rotations: 5
  output_grid: 700
  output_path: /home/dengxw/ARPES/PIMRE/test/exp_preprocessed.h5
  quadrant:
    fill_radius: 0.03
    flip_kx: true
    flip_ky: true
    smooth_radius: 0.02
  sign_correct: false
  sort_axes: true
  stride: 10
sample:
  name: RbTiBi
